### ISSUE TITLE
Integration Test Procedure Documentation

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#124]
Ticket to create a wiki page that documents procedures/assumptions/limitations associated with our integration framework. At a minimum, we need to capture how to construct the test data tarball in the format expected by the integration test shell script(s), along with how to update in S3 (once bucket is provisioned).

**Comment by david-inglish** [comment]
Added initial draft:

https://github.com/nasa/opera-sds-pge/wiki/Integration-Test-Procedure
