### ISSUE TITLE
L2_CSLC_S1 Point Release 2.1 Acceptance Test

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#139]
ADT has provided a point build update to the L2_CSLC_S1 interface delivery which means we need to run an Acceptance Test on it before it becomes the default base-image for our PGE builds.

The relevant software artifacts and documentation are available in Artifactory-FN under the following path: 

https://artifactory-fn.jpl.nasa.gov/ui/repos/tree/General/general/gov/nasa/jpl/opera/adt/cslc_s1/r2.1/interface

Since this is  a redelivery of the interface build, the existing wiki instructions should hopefully still suffice for performing the AT, but any referenced links should be updated to match the latest available artifacts in AF:

https://github.com/nasa/opera-sds-pge/wiki/CSLC-S1-Interface-Acceptance-Testing-Instructions

**Comment by david-inglish** [comment]
The wiki instructions have been updated to match the new delivery contents:
 
https://github.com/nasa/opera-sds-pge/wiki/CSLC-S1-Interface-Acceptance-Testing-Instructions

The acceptance test passes.
