### ISSUE TITLE
Fix cleanup issue with test_logger.py

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#159]
For some reason, running the test_logger.py module leaves a temporary directory (`test_logger_xxxxxtemp`) within whatever working directory the test was started in.

This ticket is to repair the test module so the temporary directory is cleaned up appropriately so we don't clutter up our working environment.

**Comment by daiangan** [comment]
I can help with this, it can probably be solved by adding __delete=True__ to __tempfile.NamedTemporaryFile()__ on line 230 of test_logger.py
However, delete is true by default, so maybe it will need some more tests to solve it.

Please let me know if I can take the ticket.

**Comment by collinss-jpl** [comment]
Hi @daiangan, if you'd like to take a shot at a fix, I'm more than happy to assign the ticket to you. Thanks for pitching in!

**Comment by daiangan** [comment]
I just submitted a pull request to fix this issue:
https://github.com/nasa/opera-sds-pge/pull/163
