### ISSUE TITLE
Rework integration test scripts to use /data/tmp for temp files

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#173]
In response to the recent issue with disk space on our CI machine, our SA provided the following:

    Hi Scott, 

    I increased /data to 300GB and added a /data/tmp directory owned by jenkins.

    Please perform any temporary work or downloads in /data/tmp rather than /tmp

This ticket is to perform the necessary changes in our existing int test scripts to use /data/tmp by default as the staging area for any S3 downloads, temporary files, etc...

**Comment by riverma** [comment]
Is `/data/tmp` cleaned automatically at a set interval? What's to stop it from filling up the disk if left unchecked?

**Comment by collinss-jpl** [comment]
> Is `/data/tmp` cleaned automatically at a set interval? What's to stop it from filling up the disk if left unchecked?

As far as I know there is no automatic cleanup in place. If it fills up I imagine we need to contact an SA to clear up space.

**Comment by collinss-jpl** [comment]
Addressed in #187
