### ISSUE TITLE
Integration shell script refactoring

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#176]
Now that a solid foundation is in place for the existing integration test shell scripts, it would be good to perform a refactoring on the existing code to minimize the redundant code before we add any additional scripts.

Things like the argument parsing logic (which _should_ be the same for all these scripts), the cleanup trap function logic, html report creation are all good candidates to be refactored into a separate shell script (`util.sh`? Or perhaps a new module so `util.sh` doesn't become a dumping ground...) and then imported into the actual int test script that captures all the particularities of the PGE/SAS to be tested.

**Comment by riverma** [comment]
Would this ticket create a script useful for I&T testing with the PCM? Or is this about something else?

**Comment by collinss-jpl** [comment]
> Would this ticket create a script useful for I&T testing with the PCM? Or is this about something else?

This is strictly about running the combined PGE/SAS docker image in isolation from the PCM, so I'm not sure how useful it would be to I&T
