### ISSUE TITLE
Develop utilities for NetCDF metadata extraction

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#182]
To facilitate population of the ISO metadata and/or assignment of file name conventions, we need to be able to extract the necessary metadata fields from the RTC-S1 output products, which in the current delivery are produced in NetCDF/HDF5 format. 

The goal of this ticket is develop the necessary utility functions to extract any arbitrary metadata field from a product using the Python HDF5 library. 

These new utilities can be included in `metadata_utils.py`, or a new module if that makes more sense.

Section 3.1 of the [RTC-S1 SAS Interface Product Spec document ](https://artifactory-fn.jpl.nasa.gov/ui/repos/tree/General/general/gov/nasa/jpl/opera/adt/rtc_s1/r1/interface/documents/OPERA_RTC_S1_R1_Product_Specs.docx) should hopefully contain all the required info on the HDF5 product structure as well as available metadata fields we should be able to extract with the new utilities.

**Comment by riverma** [comment]
Just curious @collinss-jpl whether the GitHub "New Feature" template is sufficient for your needs for tickets like this? It'd be good to use templates where ever possible (adjustments welcome).
