### ISSUE TITLE
[New Feature]: Create temp directory cleanup Jenkins pipeline

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#317]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

On the opera-pge-ci machine, we utilize the /data/tmp location to download and extract the assets used with out Integration Test pipeline. While the integration shell scripts have logic to cleanup the temporary directory created by the job, it seems that in certain circumstances the cleanup logic is not run, and /data/tmp can become cluttered with stale data owned by `jenkins:jenkins`, and hence can only be deleted by `root` (i.e. an sysadmin), or the `jenkins` account itself.

As a workaround to avoid having to constantly rely on the sysadmins to clear /data/tmp for us, it should be possible to create an additional Jenkins pipeline whose only responsibility is to remove all temporary directories within /data/tmp on the CI machine. Since Jenkins jobs run as `jenkins:jenkins`, this should bypass any permission issues.

### Describe the feature request

Create an additional Jenkins pipeline for the specific purpose of cleaning up the contents of /data/tmp on opera-pge-ci. This pipeline would then be runnable by any member of the OPERA PGE team to clear any stale data in /data/tmp that may accrue during testing of other pipelines.

**Comment by JimHofman** [comment]
Finished this.
<img width="931" alt="Screenshot 2023-07-13 at 1 41 13 PM" src="https://github.com/nasa/opera-sds-pge/assets/18269053/6d801440-6213-4b4a-8fd6-0261f8403868">

**Comment by collinss-jpl** [comment]
Resolved by #320
