### ISSUE TITLE
DISP-S1 product validation tool should have a filter for datasets to ignore during validation 

### ISSUE THREAD

**Issue by david-inglish** [nasa/opera-sds-pge#339]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Describe the feature request

The DISP-S1 validation tool checks all datasets within the product files being compared.  We need the validation tool to be configurable to ignore some datasets, specifically the contents of the runconfig in the DISP-S1 product since the paths to filenames can be different between the delivered SAS runconfig and the PGE runconfig.

**Comment by collinss-jpl** [comment]
Addressed in #344
