### ISSUE TITLE
DSWx-S1 Beta SAS Acceptance Test

### ISSUE THREAD

**Issue by sdcolli1** [nasa/opera-sds-pge#359]
Ticket to track acceptance testing for the DSWx-S1 SAS Beta delivery.

The container tarball for the delivery can be found in Artifactory-FN under the path `general/gov/nasa/jpl/opera/adt/dswx_s1/r2.1/beta/dockerimg_dswx_s1_beta_0.2.1.tar`, test inputs and expected outputs can be found under `general/gov/nasa/jpl/opera/adt/dswx_s1/r2.1/beta/sample_data.zip`. Documentation for the delivery is under `general/gov/nasa/jpl/opera/adt/dswx_s1/r2.1/beta/documents/`

A new wiki page needs to be created to capture the Acceptance Testing procedure for the Beta delivery. The procedure for the previous Interface delivery may be used as a starting point. However, unlike the previous Interface delivery, a script to compare the results of the Acceptance Test with the expected output products (within `sample_data.zip`) is now available, and its use needs to be incorporated into the testing procedure.

A copy of the DSWx-S1 comparison script can be obtained here: https://raw.githubusercontent.com/opera-adt/DSWX-SAR/main/src/dswx_sar/dswx_comparison.py

It is up to the developer to decide whether the `dswx_comparison.py` script should be executed from within the container (mounting the Acceptance Test outputs and expected outputs into the container), or from outside the container as a standalone Python process.

**Comment by collinss-jpl** [comment]
Closed by #387
