### ISSUE TITLE
DSWx Output Product Read Support

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#42]
Subtask for #40 

Part of the file name convention for DSWx-HLS products is to include the name of the originating sensor (for HLS this could be one of "Sentinel2A", "Sentinel2B"  or "Landsat8"). The simplest way for the PGE to obtain this metadata is from the output DSWx-HLS GeoTiff created by the SAS. 

According to section 4.3 of the OPERA DSWx-HLS Product Spec by ADT, there should be a SPACECRAFT_NAME metadata field which contains the appropriate value. This task is to investigate adding support for reading a generated DSWx-HLS file and extracting said metadata field. The functionality should be added to the post-processing mixin for the DSWx PGE.

**Comment by collinss-jpl** [comment]
Hi @hfattahi, question for you: do you happen to know if the field mentioned above (SPACECRAFT_NAME) is currently populated by the DSWx-HLS interface SAS, or will it come with the next release?

**Comment by hfattahi** [comment]
The current code populates the "SPACECRAFT_NAME" [here](https://github.com/opera-adt/PROTEUS/blob/main/src/proteus/dswx_hls.py#L583). 
@gshiroma do you remember if by the IF delivery, you had the SPACECRAFT_NAME populated in the product?

**Comment by gshiroma** [comment]
@hfattahi , I just checked and the IF version of the DSWx-HLS SAS should correctly populate the metadata attribute `SPACECRAFT_NAME`.
