### ISSUE TITLE
Add Output/Expected Directory Valdiation to Product Comparison Scripts

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#450]
Several of the older product comparison scripts still have TODO's in them to add validation that the defined output/expected directories exist within the container being tested. The purpose of this ticket is to add the validation checks to the scripts that are missing them. These include:

- [ ] .ci/scripts/cslc_s1/compare_cslc_s1_products.sh
- [ ] .ci/scripts/cslc_s1/compare_cslc_s1_static_products.sh
- [ ] .ci/scripts/dswx_hls/compare_dswx_hls_products.sh
- [ ] .ci/scripts/rtc_s1/compare_rtc_s1_products.sh
- [ ] .ci/scripts/rtc_s1/compare_rtc_s1_static_products.sh

An example of the validation to add can be found [here](https://github.com/nasa/opera-sds-pge/blob/23cd2da6e4040d8e95ce116bed9a8b6ad5612caa/.ci/scripts/disp_s1/compare_disp_s1_products.sh#L20-L29)

**Comment by rjbdev05** [comment]
Modified all 5 scripts, committed
