### ISSUE TITLE
DSWx-NI Beta Acceptance Test

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#478]
The delivery of the DSWx-NI Beta SAS was made on 8/2. This ticket tracks the Acceptance Testing activities for the delivery.

The [Acceptance Testing procedure page for the DSWx-NI Interface delivery](https://github.com/nasa/opera-sds-pge/wiki/DSWx%E2%80%90NI-Interface-Acceptance-Test-Instructions) may be used as a starting point, as well as a template for the new wiki page to be created with the procedure and results for the Beta delivery.

Delivered artifacts can be found under the `general/gov/nasa/jpl/opera/adt/dswx_ni/r2/beta/` path on Artifactory-FN.

**Comment by RKuttruff** [comment]
Initial runs of the acceptance tests on DEV (on both AMD and Intel instance types) resulted in numerous reported failures in the QA checks

**Comment by collinss-jpl** [comment]
Wiki page has been created here: https://github.com/nasa/opera-sds-pge/wiki/DSWx%E2%80%90NI-Beta-Acceptance-Test-Instructions

Sample AMD-based outputs provided by ADT have passed the validation check for this release, which is sufficient to call this Acceptance Test completed.
