### ISSUE TITLE
DSWx-NI PGE Engineering Release v3.0

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#488]
Ticket to track creation of Engineering Release v3.0 for the DSWx-NI PGE. This release will incorporate the "beta" delivery of the corresponding SAS.

Creation of the release should consist of the following steps:

- [x] Once beta integration branch is merged to `main`, create the `release/4.0.0-er.3.0` branch within working repository off of it
- [x] Within the release branch, update the following version numbers:
-  In `src/opera/_package.py` update "repository" version to `4.0.0-er.3.0` (`dswx_ni_pge.py` will inherit this version update by default)
- Rename `examples/dswx_ni_sample_runconfig-v4.0.0-er.2.0.yaml` to `examples/dswx_ni_sample_runconfig-v4.0.0-er.3.0.yaml` and also update the version referenced in the comment at the top of the file contents.
- [x] Push the branch to `origin`, then execute the integration test for DSWx-NI within Jenkins Int Test pipeline. Inspect the results of the .html product comparison report to ensure test is passing.
- [x] Run the Release pipeline in Jenkins to push the container images to Artifactory. For this release, ensure the "Publish Docs" option is selected.
- [x] Create a PR for the release branch. If there have been no major changes to the code (aside from version number updates), the branch can be merged immediately without review.
- [x] Pull the merged branch back into local `main`, then tag the latest commit as `4.0.0-er.3.0` and push the tag to `origin`
- [x] Create the github release page using the new tag.
- [x] Update the ICS document for the new release, and upload to Artifactory, along with the latest example RunConfig (to be completed by @collinss-jpl)

**Comment by RKuttruff** [comment]
Release here: https://github.com/nasa/opera-sds-pge/releases/tag/4.0.0-er.3.0
