### ISSUE TITLE
DSWx-S1 PGE Final Release v3.0.2

### ISSUE THREAD

**Issue by RKuttruff** [nasa/opera-sds-pge#502]
Ticket to track release of DSWx-S1 Final v3.0.2 with patched ISO XML generation.

Creation of the release should consist of the following steps:

- [x] Create the `release/3.0.2` branch within working repository off of it
- [x] Within the release branch, update the following version numbers:
-  In `src/opera/_package.py` update "repository" version to `3.0.2`
- Rename `examples/dswx_s1_sample_runconfig-v3.0.1.yaml` to `examples/dswx_s1_sample_runconfig-v3.0.2.yaml` and also update the version referenced in the comment at the top of the file contents.
- [x] Push the branch to `origin`, then execute the integration test for DSWx-S1 within Jenkins Int Test pipeline. Inspect the results of the .html product comparison report to ensure test is passing.
- [x] Run the Release pipeline in Jenkins to push the container images to Artifactory. For this release, ensure the "Publish Docs" option is selected.
- [x] Create a PR for the release branch. If there have been no major changes to the code (aside from version number updates), the branch can be merged immediately without review.
- [x] Pull the merged branch back into local `main`, then tag the latest commit as `3.0.2` and push the tag to `origin`
- [x] Create the github release page using the new tag.
- [x] Update the ICS document for the new release, and upload to Artifactory, along with the latest example RunConfig (to be completed by @collinss-jpl)

**Comment by RKuttruff** [comment]
@collinss-jpl Completed the bulk of this. Leaving the ticket marked as open for the remaining ICS update - though I don't imagine any would be needed due to the changes made.

**Comment by collinss-jpl** [comment]
ICS document has been updated and pushed to Artifactory
