### ISSUE TITLE
[Bug]: Unset ISO XML template field in runconfig leads to uncaught TypeError

### ISSUE THREAD

**Issue by RKuttruff** [nasa/opera-sds-pge#512]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

The field for the ISO XML template in the runconfig is optional (a necessity when developing Interface-stage PGEs), but there is no check for whether this is set or not in all current PGEs, which expect it to be set and exist, leading to a TypeError when trying to resolve its absolute path: `os.path.abspath(None)`

### What did you expect?

In the event the template is missing, but is needed in a given PGE, the PGE should fail gracefully with an informative error message.

### Reproducible steps

```bash
1. Produce a RunConfig YAML file with the `RunConfig.Groups.PGE.PrimaryExecutable.IsoTemplatePath` absent.
2. Run the PGE
```

**Comment by collinss-jpl** [comment]
Closed by #513
