### ISSUE TITLE
Enhancements for ISO Measured Parameters Description Schema

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#514]
As a final refinement to the automated Measured Parameter population feature for ISO XML products, I would like to see the following:

- [x] Refactor the inline schema for the Parameters Description YAML file into its own file. This file should live under `src/pge/base/schema` since it will be common to all PGEs.
- [x] Add code to `base_pge.py` to load the schema from file before validating the Parameters Description file via Yamale
- [x] Enhance the Descriptions schema file with the following additional fields:
  - An optional "display" (display_name? display_override?) field, that when provided, takes precedence over the default behavior used to "canonicalize" the parameter name. This would replace the current behavior of repeated `replace()` calls to adjust things like acronyms in parameter names
  - A required "attribute_type" field which we can use to capture the values used for the `EOS_AdditionalAttributeTypeCode` tags in the original ISO templates. This field should be an enumeration and the [allowable values](https://git.earthdata.nasa.gov/projects/EMFD/repos/iso-schemas/browse/resources/Codelist/eosCodelists.xml?at=606229ea84f207f42b7b477c507eb422f8996115#23) should match those in the `eosCodelists.xml` schema used to validate ISO products.
- [x] Update the existing Parameters Description config for DSWx-S1 to add the new fields. For the attribute_type field, reference the original values used in the current DSWx-S1 ISO template currently in the `main` branch.

**Comment by RKuttruff** [comment]
Closed by #516
