### ISSUE TITLE
Consolidation of Copyright notices

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#91]
According to JPL policy, the copyright information may be included once in a single top-level file (such as LICENCE.txt), rather than having headers in each piece of production code. This ticket is a clean up task to remove the existing copyright headers from all existing code, and ensure that the single copyright clause [here](https://github.com/nasa/opera-sds-pge/blob/main/LICENSE.txt#L190) is updated.

**Comment by ahmedsaheed** [comment]
Hi @collinss-jpl I have made a pull request at https://github.com/nasa/opera-sds-pge/pull/96
